# Generated by Django 3.2.1 on 2021-05-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_booking_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='advisor_id',
            new_name='booking_id',
        ),
    ]
