# Generated by Django 3.2.1 on 2021-05-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_advisor_id_booking_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='advisor_id',
        ),
    ]
